name: Auto Deploy on Surge

on: 
  push:
    branches: [main]
    paths:
     - 'Assignments/Assignment_01/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Import Code from Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy on Surge
        run: surge ./Assignments/Assignment_01 ammad-a1-pb2020.surge.sh --token ${{secrets.SURGE_TOKEN}}
